### ISSUE TITLE
detect «  » and add nbsp

### ISSUE THREAD

**Issue by judbd** [jolicode/JoliTypo#16]
the plugin can correct the straight quotes to add the correct french quotes and nbsp, but if a french quote is added directly, with or without space, the quote is not corrected.

example : http://fortuitement.com/test-typo/

nbsp are missing in the first « test » and «test»

**Comment by borisschapira** [comment]
Nice ! @damienalexandre, do you plan a release with this ?

**Comment by damienalexandre** [comment]
Yes very soon :+1:

**Comment by borisschapira** [comment]
Ok, waiting for the wordpress plugin update ([feature required today by a user, do you believe this ?](https://wordpress.org/support/topic/reconnaissance-des-guillemets-francais?))

**Comment by damienalexandre** [comment]
Fixed in #17

**Comment by damienalexandre** [comment]
Nice timing @borisschapira :metal: Release 0.2.0 is live, have fun :)

**Comment by borisschapira** [comment]
TypoFr for Wordpress updated :)
