### ISSUE TITLE
Check compatibility with future release of Org_Heigl_Hyphenator

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/JoliTypo#20]
- [x] There is some new stuffs to checks: https://github.com/heiglandreas/Org_Heigl_Hyphenator/commits/master
- [ ] Waiting for a release.

**Comment by hason** [comment]
What is the status of this?

**Comment by damienalexandre** [comment]
v2.0.4 have been released and it looks ok :+1: Nothing to change on JoliTypo :tada:
