### ISSUE TITLE
NoSpaceBeforeComma fixer add an unwanted space within numbers

### ISSUE THREAD

**Issue by graphidev** [jolicode/JoliTypo#28]
Hi !

By using the french floating number notation (eg: `1,2`), the _NoSpaceBeforeComma_ fixer add an unwanted space after comma. 

```
[...] « seule » 1,7 million de personnes [...]
```

is converted to :

``` html
[...] &laquo; seule &raquo; 1, 7&nbsp;million de personnes [...]
```

This has been noticed using `fr_FR` locale and the following options :

``` php
'Ellipsis', 'Dimension', 'Numeric', 'Dash',  'SmartQuotes', 'FrenchNoBreakSpace', 'NoSpaceBeforeComma',  'CurlyQuote', 'Hyphen', 'Trademark'
```

But it seems not to be a conflict between fixers nor a locale trouble (tested both in my own project and using the [demo page](http://jolitypo-demo.herokuapp.com/).)

**Comment by damienalexandre** [comment]
Thanks for the great report! I found and fixed the issue in #29 :+1:
