### ISSUE TITLE
FrenchNoBreakSpace don't force a space before [:;!\?]

### ISSUE THREAD

**Issue by masseuro** [jolicode/JoliTypo#31]
[in src/JoliTypo/Fixer/FrenchNoBreakSpace.php#L27-L28](https://github.com/jolicode/JoliTypo/blob/master/src/JoliTypo/Fixer/FrenchNoBreakSpace.php#L27-L28)

Maybe there is a reason 
have a "+" instead a "*" ? because we can't force a nbsp before a ":" if there is no space

``` php
$content = preg_replace('@['.Fixer::ALL_SPACES.']+(:)@mu', Fixer::NO_BREAK_SPACE.'$1', $content);
$content = preg_replace('@['.Fixer::ALL_SPACES.']+([;!\?])@mu', Fixer::NO_BREAK_THIN_SPACE.'$1', $content);
```

``` php
$content = preg_replace('@['.Fixer::ALL_SPACES.']*(:)@mu', Fixer::NO_BREAK_SPACE.'$1', $content);
$content = preg_replace('@['.Fixer::ALL_SPACES.']*([;!\?])@mu', Fixer::NO_BREAK_THIN_SPACE.'$1', $content);
```

**Comment by damienalexandre** [comment]
To reply on this (we already talk about it on twitter), my position on JoliTypo is to avoid breaking existing text while correcting it. In French, if someone forgot the space before the ":", adding it should be ok, but I fear it can break other contents, like smileys, emoticon shortcut `:yum:`, hours `12:44`...

What did you do in the end?

**Comment by masseuro** [comment]
I'm agree with you and it's why I think I will close this issue, this could be to much dangerous. 
Thx !

**Comment by marcimat** [comment]
Oh! I was just testing JoliTypo and I was really surprised by that too. 
It was absoutely not what I was especting ! 😊

I think I understand your point for the `:` char. 
But is it the same for others ? Sentences like `Quoi?` or `Quoi!` stays without space. 
It seems a strange default behaviour for french typography.

We can extend in fact with a custom fixer in our side. 
But maybe a sentence about that behaviour / choice could be added in the readme on #frenchnobreakspace section ?

**Comment by damienalexandre** [comment]
Hi, thanks for your valuable feedback :yum: 

We took a very careful approach on this fixer and it may be surprising. Adding a note about that on the README is more than welcome, could you send a pull request? :heart: 

Also, if you extend the fixer, feel free to post your code here for future JoliTypo users to found :yum:
