### ISSUE TITLE
Please release a new version with the Twig extension namespace fix

### ISSUE THREAD

**Issue by pounard** [jolicode/JoliTypo#39]
Hello, recently the commit https://github.com/jolicode/JoliTypo/commit/0729612b8675d563040057da4054efbc72258679 fixes a namespace problem in Twig extension PHP file. Since you didn't released it in a stable yet, each time we require the Symfony bundle using the flex recipe in Symfony 3.4 or 4, it just fails and breaks the Symfony app. When is the next release planned ?

**Comment by damienalexandre** [comment]
Release 1.0.4 is out, thanks!

**Comment by pounard** [comment]
Thank you very much!
