### ISSUE TITLE
Quotes for Switzerland are not correct

### ISSUE THREAD

**Issue by georgobermayr** [jolicode/JoliTypo#46]
Hi,

the quotes for the de-CH locale are not set correctly. The quotes for Germany and Austria are applied wich is not correct for Switzerland. In Switzerland they use French-style angle quotation marks, see: https://en.wikipedia.org/wiki/Quotation_mark#German

> In Switzerland, however, the French-style angle quotation mark sets are also used for German printed text: «A ‹B›?»
> Andreas fragte mich: «Hast du den Artikel ‹EU-Erweiterung› gelesen?»
> Andreas asked me: ‘Have you read the “EU Expansion” article?’

**Comment by damienalexandre** [comment]
Thanks for the feedback!

This exception can be added here:

https://github.com/jolicode/JoliTypo/blob/323e0d0844f15f2191f784bc6863281c68d2fd59/src/JoliTypo/Fixer/SmartQuotes.php#L59-L68

Would you like to suggest a pull request?

**Comment by georgobermayr** [comment]
Thank you! Pull request is ready for review.

**Comment by damienalexandre** [comment]
Thanks, I just release version 1.0.5 with your fix!
Cheers
