### ISSUE TITLE
Fix autoload of tests classes with composer

### ISSUE THREAD

**Issue by killerwolf** [jolicode/JoliTypo#49]
Composer with version 1.0.5 of joliTypo gives the following notice, seems concerning mainly Tests Classes.

`Deprecation Notice: Class JoliTypo\Fixer\FrenchQuotes located in ./vendor/jolicode/jolitypo/src/JoliTypo/Fixer/FrenchQuotes.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///var/www/PROJECT/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185`

**Comment by killerwolf** [comment]
@damienalexandre  do you plan on creating a tag, the last one is 2 years old

**Comment by damienalexandre** [comment]
The latest release is from July 2019, but you are right about pushing a new release as we have some pending change: https://github.com/jolicode/JoliTypo/compare/1.0.5...master

Thanks for the ping, I'm planning this very soon.

**Comment by damienalexandre** [comment]
Here you go, version 1.1.0 is out!

https://packagist.org/packages/jolicode/jolitypo#1.1.0
