### ISSUE TITLE
Add gender-neutral Filter to handle interpuncts in French

### ISSUE THREAD

**Issue by MarionLeHerisson** [jolicode/JoliTypo#56]
Replaces the usual dot `.` with an interpunct `·` in gender-neutral words.

`musicien.ne.s` would become `musicien·ne·s`

See [this Wikipedia article](https://fr.wikipedia.org/wiki/Langage_%C3%A9pic%C3%A8ne#Fran%C3%A7ais)

**Comment by lyrixx** [comment]
Would you mind submitting a PR? :D

**Comment by pounard** [comment]
Wouldn't it be best to have a filter replacing `musicien.ne.s` with `musiciennes et musciens` ?

Just trolling :trollface: :smile:

**Comment by MrYamous** [comment]
I can think of two other contexts in which we can find full dot usage in french that are not related to inclusive writing, domain names and files extensions. 

If we consider as exemples `github.com`  `home.html.twig` `musicien.ne.s` only the last one should be modified, but I don't know if we can find a rule that can differentiate them to apply a fixer when it's relevant
