### ISSUE TITLE
Add an "unfix" method

### ISSUE THREAD

**Issue by MarionLeHerisson** [jolicode/JoliTypo#70]
If, for some reason, I want to get the ugly keyboard typed text back, then I would like to use something like 
```PHP
$fixer->unfix($fixedText);
```

Using this method, I could even "unfix" some parts of the fixed text and keep the rest. (Like removing the hyphenation while keeping the Smart Quotes)

**Comment by pyrech** [comment]
Looks like there is not a real need for this feature yet. Thanks for your contribution. Feel free to reopen the issue if you have more insight to share.
