### ISSUE TITLE
issue deconding special character

### ISSUE THREAD

**Issue by lalop** [jolicode/JoliTypo#93]
I get a strange result when I have the character œ in a string the string seems to be returned in a different encoding.
Currently I reproduce the issue on a server but not in local. I think the issue come from the php configuration but I can't find what's wrong yet.

I reproduce the issue on the demo too https://jolitypo.jolicode.com/, using the french locale, applying all fixes and pasting the string `<p>des œuvres d'art.</p>`

**Comment by damienalexandre** [comment]
Hello!

Thanks for the report, can you tell us which PHP Version you are using?

Is JoliTypo up to date? 

We made a change here: https://github.com/jolicode/JoliTypo/commit/4b458bad0cda37b6ac10a772ad574edf1d9b0f69 that may affect the behavior of JoliTypo.

**Comment by damienalexandre** [comment]
You are right about the issue happening on the demo website, but I'm not able to reproduce with the latest JoliTypo version.

I opened a PR to add your example as a test: https://github.com/jolicode/JoliTypo/pull/94

Tests are green on all supported PHP versions.

Can you run `composer info jolicode/jolitypo` on your project and post the result here?

**Comment by lalop** [comment]
I'm using php 8.0 locally and  8.1.16 on the serveur, it seems to be linked with some comments in the commit.
I was using jolitypo 1.3.0, I do not reproduce the issue on 1.4.0. Thank you for your comment
