### ISSUE TITLE
Add Dark Mode to the website

### ISSUE THREAD

**Issue by singodiyashubham87** [jolicode/JoliTypo#98]
I want to add a toggle theme option to the website to let the user toggle between light and dark mode.

**Comment by lyrixx** [comment]
Good idea! Do you want to give it a try? 
The repo is [open source](https://github.com/jolicode/jolitypo-website)

**Comment by singodiyashubham87** [comment]
@lyrixx Indeed I want to work on this issue.

**Comment by lyrixx** [comment]
Thanks again 💛

I'm closing this issue here since you'll create a PR there.

**Comment by singodiyashubham87** [comment]
@lyrixx But I'm still not assigned the issue, How can I start working?

**Comment by lyrixx** [comment]
You need 
* clone the [repository](https://github.com/jolicode/jolitypo-website)
* follow README's instruction
* start hacking the project.

**Comment by singodiyashubham87** [comment]
@lyrixx I'm facing this error, can you tell me what can be the possible reason behind this error?
![image](https://github.com/jolicode/JoliTypo/assets/93720428/d49c8d77-c584-40ef-a020-291275a7fb6b)

**Comment by lyrixx** [comment]
This is really strange. I cleaned up my project, and try to follow the README, and it works as expected:

```
>…olicode/jolitypo-website(master) git clean -fdx
Removing .phpunit.result.cache
Removing assets/controllers/
Removing node_modules/
Removing public/build/
Removing var/
Removing vendor/
>…olicode/jolitypo-website(master) composer install &>/dev/null
>…olicode/jolitypo-website(master) yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > sass-loader@12.6.0" has unmet peer dependency "webpack@^5.0.0".
[4/4] Building fresh packages...
Done in 1.79s.
```

is your yarn outdated? instead of `yarn install`, can you try `yarn` ?

**Comment by singodiyashubham87** [comment]
@lyrixx 
![image](https://github.com/jolicode/JoliTypo/assets/93720428/3c80461f-8325-4bb9-b93f-364ba1ad356d)

**Comment by lyrixx** [comment]
Never seen that. you can try with NPM instead.

**Comment by singodiyashubham87** [comment]
@lyrixx Using "npm install", the packages are installed and on running "npm run dev", It's showing this output
![image](https://github.com/jolicode/JoliTypo/assets/93720428/a5fd25d0-3337-408b-87bb-4996d0d97d7a)

**Comment by lyrixx** [comment]
Perfect 👍🏼

**Comment by lyrixx** [comment]
https://github.com/jolicode/JoliTypo-website#installation

**Comment by singodiyashubham87** [comment]
@lyrixx 
![image](https://github.com/jolicode/JoliTypo/assets/93720428/a2882719-7432-4ba8-88c6-be9c19900671)
